services:
  db:
    image: postgres:18rc1-alpine
    container_name: iot_postgres_db
    environment:
      POSTGRES_DB: iot_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iot_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: iot_node_server
    environment:
      DB_NAME: iot_database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      HOST: "0.0.0.0"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - iot_network

  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
    container_name: iot_spa
    environment:
      REACT_APP_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge

volumes:
  pgdata: